/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.com.vw.jhanlos.ads.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import mx.com.vw.jhanlos.ads.model.Propertie;
import mx.com.vw.jhanlos.ads.model.PropertieModel;
import mx.com.vw.jhanlos.ads.model.PropertieSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Propertie service. Represents a row in the &quot;vwm_ads_Propertie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link mx.com.vw.jhanlos.ads.model.PropertieModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PropertieImpl}.
 * </p>
 *
 * @author Jorge Loayza
 * @see PropertieImpl
 * @see mx.com.vw.jhanlos.ads.model.Propertie
 * @see mx.com.vw.jhanlos.ads.model.PropertieModel
 * @generated
 */
@JSON(strict = true)
public class PropertieModelImpl extends BaseModelImpl<Propertie>
	implements PropertieModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a propertie model instance should use the {@link mx.com.vw.jhanlos.ads.model.Propertie} interface instead.
	 */
	public static final String TABLE_NAME = "vwm_ads_Propertie";
	public static final Object[][] TABLE_COLUMNS = {
			{ "propertieId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.BIGINT },
			{ "modifiedDate", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "value", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table vwm_ads_Propertie (propertieId LONG not null primary key,companyId LONG,userId LONG,createDate LONG,modifiedDate LONG,name VARCHAR(75) null,value VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table vwm_ads_Propertie";
	public static final String ORDER_BY_JPQL = " ORDER BY propertie.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vwm_ads_Propertie.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.mx.com.vw.jhanlos.ads.model.Propertie"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.mx.com.vw.jhanlos.ads.model.Propertie"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Propertie toModel(PropertieSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Propertie model = new PropertieImpl();

		model.setPropertieId(soapModel.getPropertieId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setValue(soapModel.getValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Propertie> toModels(PropertieSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Propertie> models = new ArrayList<Propertie>(soapModels.length);

		for (PropertieSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.mx.com.vw.jhanlos.ads.model.Propertie"));

	public PropertieModelImpl() {
	}

	public long getPrimaryKey() {
		return _propertieId;
	}

	public void setPrimaryKey(long primaryKey) {
		setPropertieId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_propertieId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Propertie.class;
	}

	public String getModelClassName() {
		return Propertie.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("propertieId", getPropertieId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("value", getValue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long propertieId = (Long)attributes.get("propertieId");

		if (propertieId != null) {
			setPropertieId(propertieId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long createDate = (Long)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long modifiedDate = (Long)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String value = (String)attributes.get("value");

		if (value != null) {
			setValue(value);
		}
	}

	@JSON
	public long getPropertieId() {
		return _propertieId;
	}

	public void setPropertieId(long propertieId) {
		_propertieId = propertieId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public long getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(long createDate) {
		_createDate = createDate;
	}

	@JSON
	public long getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(long modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@JSON
	public String getValue() {
		if (_value == null) {
			return StringPool.BLANK;
		}
		else {
			return _value;
		}
	}

	public void setValue(String value) {
		_value = value;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Propertie.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Propertie toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Propertie)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PropertieImpl propertieImpl = new PropertieImpl();

		propertieImpl.setPropertieId(getPropertieId());
		propertieImpl.setCompanyId(getCompanyId());
		propertieImpl.setUserId(getUserId());
		propertieImpl.setCreateDate(getCreateDate());
		propertieImpl.setModifiedDate(getModifiedDate());
		propertieImpl.setName(getName());
		propertieImpl.setValue(getValue());

		propertieImpl.resetOriginalValues();

		return propertieImpl;
	}

	public int compareTo(Propertie propertie) {
		int value = 0;

		value = getName().compareTo(propertie.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Propertie propertie = null;

		try {
			propertie = (Propertie)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = propertie.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Propertie> toCacheModel() {
		PropertieCacheModel propertieCacheModel = new PropertieCacheModel();

		propertieCacheModel.propertieId = getPropertieId();

		propertieCacheModel.companyId = getCompanyId();

		propertieCacheModel.userId = getUserId();

		propertieCacheModel.createDate = getCreateDate();

		propertieCacheModel.modifiedDate = getModifiedDate();

		propertieCacheModel.name = getName();

		String name = propertieCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			propertieCacheModel.name = null;
		}

		propertieCacheModel.value = getValue();

		String value = propertieCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			propertieCacheModel.value = null;
		}

		return propertieCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{propertieId=");
		sb.append(getPropertieId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", value=");
		sb.append(getValue());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("mx.com.vw.jhanlos.ads.model.Propertie");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>propertieId</column-name><column-value><![CDATA[");
		sb.append(getPropertieId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Propertie.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Propertie.class
		};
	private long _propertieId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _createDate;
	private long _modifiedDate;
	private String _name;
	private String _value;
	private Propertie _escapedModelProxy;
}