/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.com.vw.jhanlos.ads.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Propertie service. Represents a row in the &quot;vwm_ads_Propertie&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link mx.com.vw.jhanlos.ads.model.impl.PropertieModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link mx.com.vw.jhanlos.ads.model.impl.PropertieImpl}.
 * </p>
 *
 * @author Jorge Loayza
 * @see Propertie
 * @see mx.com.vw.jhanlos.ads.model.impl.PropertieImpl
 * @see mx.com.vw.jhanlos.ads.model.impl.PropertieModelImpl
 * @generated
 */
public interface PropertieModel extends BaseModel<Propertie> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a propertie model instance should use the {@link Propertie} interface instead.
	 */

	/**
	 * Returns the primary key of this propertie.
	 *
	 * @return the primary key of this propertie
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this propertie.
	 *
	 * @param primaryKey the primary key of this propertie
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the propertie ID of this propertie.
	 *
	 * @return the propertie ID of this propertie
	 */
	public long getPropertieId();

	/**
	 * Sets the propertie ID of this propertie.
	 *
	 * @param propertieId the propertie ID of this propertie
	 */
	public void setPropertieId(long propertieId);

	/**
	 * Returns the company ID of this propertie.
	 *
	 * @return the company ID of this propertie
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this propertie.
	 *
	 * @param companyId the company ID of this propertie
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this propertie.
	 *
	 * @return the user ID of this propertie
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this propertie.
	 *
	 * @param userId the user ID of this propertie
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this propertie.
	 *
	 * @return the user uuid of this propertie
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this propertie.
	 *
	 * @param userUuid the user uuid of this propertie
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this propertie.
	 *
	 * @return the create date of this propertie
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this propertie.
	 *
	 * @param createDate the create date of this propertie
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the modified date of this propertie.
	 *
	 * @return the modified date of this propertie
	 */
	public long getModifiedDate();

	/**
	 * Sets the modified date of this propertie.
	 *
	 * @param modifiedDate the modified date of this propertie
	 */
	public void setModifiedDate(long modifiedDate);

	/**
	 * Returns the name of this propertie.
	 *
	 * @return the name of this propertie
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this propertie.
	 *
	 * @param name the name of this propertie
	 */
	public void setName(String name);

	/**
	 * Returns the value of this propertie.
	 *
	 * @return the value of this propertie
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this propertie.
	 *
	 * @param value the value of this propertie
	 */
	public void setValue(String value);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Propertie propertie);

	public int hashCode();

	public CacheModel<Propertie> toCacheModel();

	public Propertie toEscapedModel();

	public String toString();

	public String toXmlString();
}