/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Filelog service. Represents a row in the &quot;CONSIS_TRACK_Filelog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.FilelogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.FilelogImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see Filelog
 * @see com.liferay.consistent.tracking.model.impl.FilelogImpl
 * @see com.liferay.consistent.tracking.model.impl.FilelogModelImpl
 * @generated
 */
public interface FilelogModel extends BaseModel<Filelog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a filelog model instance should use the {@link Filelog} interface instead.
	 */

	/**
	 * Returns the primary key of this filelog.
	 *
	 * @return the primary key of this filelog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this filelog.
	 *
	 * @param primaryKey the primary key of this filelog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the filelog ID of this filelog.
	 *
	 * @return the filelog ID of this filelog
	 */
	public long getFilelogId();

	/**
	 * Sets the filelog ID of this filelog.
	 *
	 * @param FilelogId the filelog ID of this filelog
	 */
	public void setFilelogId(long FilelogId);

	/**
	 * Returns the company ID of this filelog.
	 *
	 * @return the company ID of this filelog
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this filelog.
	 *
	 * @param companyId the company ID of this filelog
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the guest of this filelog.
	 *
	 * @return the guest of this filelog
	 */
	public boolean getGuest();

	/**
	 * Returns <code>true</code> if this filelog is guest.
	 *
	 * @return <code>true</code> if this filelog is guest; <code>false</code> otherwise
	 */
	public boolean isGuest();

	/**
	 * Sets whether this filelog is guest.
	 *
	 * @param guest the guest of this filelog
	 */
	public void setGuest(boolean guest);

	/**
	 * Returns the userlog ID of this filelog.
	 *
	 * @return the userlog ID of this filelog
	 */
	public long getUserlogId();

	/**
	 * Sets the userlog ID of this filelog.
	 *
	 * @param userlogId the userlog ID of this filelog
	 */
	public void setUserlogId(long userlogId);

	/**
	 * Returns the file ID of this filelog.
	 *
	 * @return the file ID of this filelog
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this filelog.
	 *
	 * @param fileId the file ID of this filelog
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the file version of this filelog.
	 *
	 * @return the file version of this filelog
	 */
	@AutoEscape
	public String getFileVersion();

	/**
	 * Sets the file version of this filelog.
	 *
	 * @param fileVersion the file version of this filelog
	 */
	public void setFileVersion(String fileVersion);

	/**
	 * Returns the access date of this filelog.
	 *
	 * @return the access date of this filelog
	 */
	public long getAccessDate();

	/**
	 * Sets the access date of this filelog.
	 *
	 * @param accessDate the access date of this filelog
	 */
	public void setAccessDate(long accessDate);

	/**
	 * Returns the elapse load of this filelog.
	 *
	 * @return the elapse load of this filelog
	 */
	public long getElapseLoad();

	/**
	 * Sets the elapse load of this filelog.
	 *
	 * @param elapseLoad the elapse load of this filelog
	 */
	public void setElapseLoad(long elapseLoad);

	/**
	 * Returns the trafic of this filelog.
	 *
	 * @return the trafic of this filelog
	 */
	public boolean getTrafic();

	/**
	 * Returns <code>true</code> if this filelog is trafic.
	 *
	 * @return <code>true</code> if this filelog is trafic; <code>false</code> otherwise
	 */
	public boolean isTrafic();

	/**
	 * Sets whether this filelog is trafic.
	 *
	 * @param trafic the trafic of this filelog
	 */
	public void setTrafic(boolean trafic);

	/**
	 * Returns the status of this filelog.
	 *
	 * @return the status of this filelog
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this filelog is status.
	 *
	 * @return <code>true</code> if this filelog is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this filelog is status.
	 *
	 * @param status the status of this filelog
	 */
	public void setStatus(boolean status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Filelog filelog);

	public int hashCode();

	public CacheModel<Filelog> toCacheModel();

	public Filelog toEscapedModel();

	public String toString();

	public String toXmlString();
}