/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OS service. Represents a row in the &quot;CONSIS_TRACK_OS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.OSModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.OSImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see OS
 * @see com.liferay.consistent.tracking.model.impl.OSImpl
 * @see com.liferay.consistent.tracking.model.impl.OSModelImpl
 * @generated
 */
public interface OSModel extends BaseModel<OS> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a o s model instance should use the {@link OS} interface instead.
	 */

	/**
	 * Returns the primary key of this o s.
	 *
	 * @return the primary key of this o s
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this o s.
	 *
	 * @param primaryKey the primary key of this o s
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the os ID of this o s.
	 *
	 * @return the os ID of this o s
	 */
	public long getOsId();

	/**
	 * Sets the os ID of this o s.
	 *
	 * @param osId the os ID of this o s
	 */
	public void setOsId(long osId);

	/**
	 * Returns the name of this o s.
	 *
	 * @return the name of this o s
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this o s.
	 *
	 * @param name the name of this o s
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(OS os);

	public int hashCode();

	public CacheModel<OS> toCacheModel();

	public OS toEscapedModel();

	public String toString();

	public String toXmlString();
}