/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortletHit service. Represents a row in the &quot;CONSIS_TRACK_PortletHit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.PortletHitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.PortletHitImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see PortletHit
 * @see com.liferay.consistent.tracking.model.impl.PortletHitImpl
 * @see com.liferay.consistent.tracking.model.impl.PortletHitModelImpl
 * @generated
 */
public interface PortletHitModel extends BaseModel<PortletHit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portlet hit model instance should use the {@link PortletHit} interface instead.
	 */

	/**
	 * Returns the primary key of this portlet hit.
	 *
	 * @return the primary key of this portlet hit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this portlet hit.
	 *
	 * @param primaryKey the primary key of this portlet hit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hit ID of this portlet hit.
	 *
	 * @return the hit ID of this portlet hit
	 */
	public long getHitId();

	/**
	 * Sets the hit ID of this portlet hit.
	 *
	 * @param hitId the hit ID of this portlet hit
	 */
	public void setHitId(long hitId);

	/**
	 * Returns the company ID of this portlet hit.
	 *
	 * @return the company ID of this portlet hit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this portlet hit.
	 *
	 * @param companyId the company ID of this portlet hit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the portlet ID of this portlet hit.
	 *
	 * @return the portlet ID of this portlet hit
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this portlet hit.
	 *
	 * @param portletId the portlet ID of this portlet hit
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the guest of this portlet hit.
	 *
	 * @return the guest of this portlet hit
	 */
	public boolean getGuest();

	/**
	 * Returns <code>true</code> if this portlet hit is guest.
	 *
	 * @return <code>true</code> if this portlet hit is guest; <code>false</code> otherwise
	 */
	public boolean isGuest();

	/**
	 * Sets whether this portlet hit is guest.
	 *
	 * @param guest the guest of this portlet hit
	 */
	public void setGuest(boolean guest);

	/**
	 * Returns the user ID of this portlet hit.
	 *
	 * @return the user ID of this portlet hit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this portlet hit.
	 *
	 * @param userId the user ID of this portlet hit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portlet hit.
	 *
	 * @return the user uuid of this portlet hit
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this portlet hit.
	 *
	 * @param userUuid the user uuid of this portlet hit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the userlog ID of this portlet hit.
	 *
	 * @return the userlog ID of this portlet hit
	 */
	public long getUserlogId();

	/**
	 * Sets the userlog ID of this portlet hit.
	 *
	 * @param userlogId the userlog ID of this portlet hit
	 */
	public void setUserlogId(long userlogId);

	/**
	 * Returns the access date of this portlet hit.
	 *
	 * @return the access date of this portlet hit
	 */
	public long getAccessDate();

	/**
	 * Sets the access date of this portlet hit.
	 *
	 * @param accessDate the access date of this portlet hit
	 */
	public void setAccessDate(long accessDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PortletHit portletHit);

	public int hashCode();

	public CacheModel<PortletHit> toCacheModel();

	public PortletHit toEscapedModel();

	public String toString();

	public String toXmlString();
}