/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortletProperty service. Represents a row in the &quot;CONSIS_TRACK_PortletProperty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.PortletPropertyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.PortletPropertyImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see PortletProperty
 * @see com.liferay.consistent.tracking.model.impl.PortletPropertyImpl
 * @see com.liferay.consistent.tracking.model.impl.PortletPropertyModelImpl
 * @generated
 */
public interface PortletPropertyModel extends BaseModel<PortletProperty> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portlet property model instance should use the {@link PortletProperty} interface instead.
	 */

	/**
	 * Returns the primary key of this portlet property.
	 *
	 * @return the primary key of this portlet property
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this portlet property.
	 *
	 * @param primaryKey the primary key of this portlet property
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the property ID of this portlet property.
	 *
	 * @return the property ID of this portlet property
	 */
	public long getPropertyId();

	/**
	 * Sets the property ID of this portlet property.
	 *
	 * @param propertyId the property ID of this portlet property
	 */
	public void setPropertyId(long propertyId);

	/**
	 * Returns the company ID of this portlet property.
	 *
	 * @return the company ID of this portlet property
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this portlet property.
	 *
	 * @param companyId the company ID of this portlet property
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this portlet property.
	 *
	 * @return the name of this portlet property
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this portlet property.
	 *
	 * @param name the name of this portlet property
	 */
	public void setName(String name);

	/**
	 * Returns the value of this portlet property.
	 *
	 * @return the value of this portlet property
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this portlet property.
	 *
	 * @param value the value of this portlet property
	 */
	public void setValue(String value);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PortletProperty portletProperty);

	public int hashCode();

	public CacheModel<PortletProperty> toCacheModel();

	public PortletProperty toEscapedModel();

	public String toString();

	public String toXmlString();
}