/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SearchWordHit service. Represents a row in the &quot;CONSIS_TRACK_SearchWordHit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.SearchWordHitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.SearchWordHitImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see SearchWordHit
 * @see com.liferay.consistent.tracking.model.impl.SearchWordHitImpl
 * @see com.liferay.consistent.tracking.model.impl.SearchWordHitModelImpl
 * @generated
 */
public interface SearchWordHitModel extends BaseModel<SearchWordHit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search word hit model instance should use the {@link SearchWordHit} interface instead.
	 */

	/**
	 * Returns the primary key of this search word hit.
	 *
	 * @return the primary key of this search word hit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search word hit.
	 *
	 * @param primaryKey the primary key of this search word hit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hit ID of this search word hit.
	 *
	 * @return the hit ID of this search word hit
	 */
	public long getHitId();

	/**
	 * Sets the hit ID of this search word hit.
	 *
	 * @param hitId the hit ID of this search word hit
	 */
	public void setHitId(long hitId);

	/**
	 * Returns the company ID of this search word hit.
	 *
	 * @return the company ID of this search word hit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this search word hit.
	 *
	 * @param companyId the company ID of this search word hit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the word ID of this search word hit.
	 *
	 * @return the word ID of this search word hit
	 */
	public long getWordId();

	/**
	 * Sets the word ID of this search word hit.
	 *
	 * @param wordId the word ID of this search word hit
	 */
	public void setWordId(long wordId);

	/**
	 * Returns the guest of this search word hit.
	 *
	 * @return the guest of this search word hit
	 */
	public boolean getGuest();

	/**
	 * Returns <code>true</code> if this search word hit is guest.
	 *
	 * @return <code>true</code> if this search word hit is guest; <code>false</code> otherwise
	 */
	public boolean isGuest();

	/**
	 * Sets whether this search word hit is guest.
	 *
	 * @param guest the guest of this search word hit
	 */
	public void setGuest(boolean guest);

	/**
	 * Returns the access date of this search word hit.
	 *
	 * @return the access date of this search word hit
	 */
	public long getAccessDate();

	/**
	 * Sets the access date of this search word hit.
	 *
	 * @param accessDate the access date of this search word hit
	 */
	public void setAccessDate(long accessDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SearchWordHit searchWordHit);

	public int hashCode();

	public CacheModel<SearchWordHit> toCacheModel();

	public SearchWordHit toEscapedModel();

	public String toString();

	public String toXmlString();
}