/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TrackEvent service. Represents a row in the &quot;CONSIS_TRACK_TrackEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.TrackEventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.TrackEventImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see TrackEvent
 * @see com.liferay.consistent.tracking.model.impl.TrackEventImpl
 * @see com.liferay.consistent.tracking.model.impl.TrackEventModelImpl
 * @generated
 */
public interface TrackEventModel extends BaseModel<TrackEvent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a track event model instance should use the {@link TrackEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this track event.
	 *
	 * @return the primary key of this track event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this track event.
	 *
	 * @param primaryKey the primary key of this track event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the track event ID of this track event.
	 *
	 * @return the track event ID of this track event
	 */
	public long getTrackEventId();

	/**
	 * Sets the track event ID of this track event.
	 *
	 * @param trackEventId the track event ID of this track event
	 */
	public void setTrackEventId(long trackEventId);

	/**
	 * Returns the company ID of this track event.
	 *
	 * @return the company ID of this track event
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this track event.
	 *
	 * @param companyId the company ID of this track event
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user name of this track event.
	 *
	 * @return the user name of this track event
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this track event.
	 *
	 * @param userName the user name of this track event
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this track event.
	 *
	 * @return the create date of this track event
	 */
	public long getCreateDate();

	/**
	 * Sets the create date of this track event.
	 *
	 * @param createDate the create date of this track event
	 */
	public void setCreateDate(long createDate);

	/**
	 * Returns the userlog ID of this track event.
	 *
	 * @return the userlog ID of this track event
	 */
	public long getUserlogId();

	/**
	 * Sets the userlog ID of this track event.
	 *
	 * @param userlogId the userlog ID of this track event
	 */
	public void setUserlogId(long userlogId);

	/**
	 * Returns the event type of this track event.
	 *
	 * @return the event type of this track event
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this track event.
	 *
	 * @param eventType the event type of this track event
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the class name of this track event.
	 *
	 * @return the class name of this track event
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this track event.
	 *
	 * @param className the class name of this track event
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this track event.
	 *
	 * @return the class p k of this track event
	 */
	@AutoEscape
	public String getClassPK();

	/**
	 * Sets the class p k of this track event.
	 *
	 * @param classPK the class p k of this track event
	 */
	public void setClassPK(String classPK);

	/**
	 * Returns the message of this track event.
	 *
	 * @return the message of this track event
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this track event.
	 *
	 * @param message the message of this track event
	 */
	public void setMessage(String message);

	/**
	 * Returns the client host of this track event.
	 *
	 * @return the client host of this track event
	 */
	@AutoEscape
	public String getClientHost();

	/**
	 * Sets the client host of this track event.
	 *
	 * @param clientHost the client host of this track event
	 */
	public void setClientHost(String clientHost);

	/**
	 * Returns the client addr of this track event.
	 *
	 * @return the client addr of this track event
	 */
	@AutoEscape
	public String getClientAddr();

	/**
	 * Sets the client addr of this track event.
	 *
	 * @param clientAddr the client addr of this track event
	 */
	public void setClientAddr(String clientAddr);

	/**
	 * Returns the server name of this track event.
	 *
	 * @return the server name of this track event
	 */
	@AutoEscape
	public String getServerName();

	/**
	 * Sets the server name of this track event.
	 *
	 * @param serverName the server name of this track event
	 */
	public void setServerName(String serverName);

	/**
	 * Returns the server port of this track event.
	 *
	 * @return the server port of this track event
	 */
	public int getServerPort();

	/**
	 * Sets the server port of this track event.
	 *
	 * @param serverPort the server port of this track event
	 */
	public void setServerPort(int serverPort);

	/**
	 * Returns the additional info of this track event.
	 *
	 * @return the additional info of this track event
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this track event.
	 *
	 * @param additionalInfo the additional info of this track event
	 */
	public void setAdditionalInfo(String additionalInfo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TrackEvent trackEvent);

	public int hashCode();

	public CacheModel<TrackEvent> toCacheModel();

	public TrackEvent toEscapedModel();

	public String toString();

	public String toXmlString();
}