/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.consistent.tracking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Word service. Represents a row in the &quot;CONSIS_TRACK_Word&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consistent.tracking.model.impl.WordModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consistent.tracking.model.impl.WordImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see Word
 * @see com.liferay.consistent.tracking.model.impl.WordImpl
 * @see com.liferay.consistent.tracking.model.impl.WordModelImpl
 * @generated
 */
public interface WordModel extends BaseModel<Word> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a word model instance should use the {@link Word} interface instead.
	 */

	/**
	 * Returns the primary key of this word.
	 *
	 * @return the primary key of this word
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this word.
	 *
	 * @param primaryKey the primary key of this word
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the word ID of this word.
	 *
	 * @return the word ID of this word
	 */
	public long getWordId();

	/**
	 * Sets the word ID of this word.
	 *
	 * @param wordId the word ID of this word
	 */
	public void setWordId(long wordId);

	/**
	 * Returns the word name of this word.
	 *
	 * @return the word name of this word
	 */
	@AutoEscape
	public String getWordName();

	/**
	 * Sets the word name of this word.
	 *
	 * @param wordName the word name of this word
	 */
	public void setWordName(String wordName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Word word);

	public int hashCode();

	public CacheModel<Word> toCacheModel();

	public Word toEscapedModel();

	public String toString();

	public String toXmlString();
}